# Generated by Django 5.1.15 on 2026-03-24 05:00

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyDeliveryInputSnapshot",
            fields=[
                (
                    "daily_delivery_input_snapshot_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField()),
                ("fleet_id", models.UUIDField()),
                ("driver_id", models.UUIDField()),
                ("service_date", models.DateField()),
                ("delivery_count", models.PositiveIntegerField()),
                (
                    "total_distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "total_base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("source_record_count", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("superseded", "superseded")],
                        max_length=32,
                    ),
                ),
            ],
            options={
                "ordering": ("service_date", "daily_delivery_input_snapshot_id"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("company_id", "fleet_id", "driver_id", "service_date"),
                        name="unique_active_daily_delivery_input_snapshot_per_scope_and_date",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeliveryRecord",
            fields=[
                (
                    "delivery_record_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField()),
                ("fleet_id", models.UUIDField()),
                ("driver_id", models.UUIDField()),
                ("service_date", models.DateField()),
                ("source_reference", models.CharField(max_length=128)),
                ("delivery_count", models.PositiveIntegerField()),
                (
                    "distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("confirmed", "confirmed"),
                            ("void", "void"),
                        ],
                        max_length=32,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ("service_date", "delivery_record_id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "company_id",
                            "fleet_id",
                            "driver_id",
                            "service_date",
                            "source_reference",
                        ),
                        name="unique_delivery_record_source_reference_per_scope_and_date",
                    )
                ],
            },
        ),
    ]
